[package]
name = "micro-host-esp32"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
micro-core.workspace = true
micro-ir.workspace = true
micro-lvgl = { path = "../micro-lvgl" }
micro-os-core.workspace = true

[dev-dependencies]
micro-compiler = { path = "../micro-compiler" }
