[workspace]
members = [
  "crates/micro-os-core",
  "crates/micro-board-profile",
  "crates/micro-ir",
  "crates/micro-vm",
  "crates/micro-core",
  "crates/micro-compiler",
  "crates/micro-lvgl",
  "crates/micro-host-sdl",
  "crates/micro-renderer-web",
  "crates/micro-host-web",
  "crates/micro-host-esp32",
  "crates/micro-store",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
micro-os-core = { path = "crates/micro-os-core" }
micro-ir = { path = "crates/micro-ir" }
micro-vm = { path = "crates/micro-vm" }
micro-core = { path = "crates/micro-core" }
micro-store = { path = "crates/micro-store" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
