#!/usr/bin/env python3
"""Generate the shared Micro UI font manifest and platform assets."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
FONT_DIRECTORY = REPOSITORY_ROOT / "assets/fonts"
MANIFEST_PATH = FONT_DIRECTORY / "ui-sans-common.txt"
METADATA_PATH = FONT_DIRECTORY / "noto-sans-sc.json"
LICENSE_PATH = FONT_DIRECTORY / "OFL-1.1.txt"
SOURCE_PATH = REPOSITORY_ROOT / "work/fonts/NotoSansCJKsc-Regular.otf"
PYTHON_TOOLS = REPOSITORY_ROOT / "work/tools/python"
LV_FONT_CONV = (
    REPOSITORY_ROOT / "work/tools/lv-font-conv/node_modules/.bin/lv_font_conv"
)
WEB_FONT_PATH = (
    REPOSITORY_ROOT
    / "products/micro-web-player/public/fonts/micro-ui-sans-common.woff2"
)
LVGL_DIRECTORY = FONT_DIRECTORY / "lvgl"
LVGL_SIZES_PATH = LVGL_DIRECTORY / "micro_ui_sans_sizes.json"
LV_FONT_CONV_LOCK = FONT_DIRECTORY / "lv-font-conv-lock.json"
INSTALLED_LV_FONT_CONV_LOCK = REPOSITORY_ROOT / "work/tools/lv-font-conv/node_modules/.package-lock.json"
FONT_SIZES = (12, 14, 18, 24, 32)
LVGL_BPP = 2
CHINESE_PUNCTUATION = tuple(
    "·—‘’“”…、。〈〉《》「」『』【】〔〕！（），．：；？"
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def gb2312_level_one_han() -> tuple[str, ...]:
    glyphs: list[str] = []
    for lead in range(0xB0, 0xD8):
        for trail in range(0xA1, 0xFF):
            try:
                glyph = bytes((lead, trail)).decode("gb2312")
            except UnicodeDecodeError:
                continue
            if len(glyph) == 1 and "\u4e00" <= glyph <= "\u9fff":
                glyphs.append(glyph)
    unique = tuple(sorted(set(glyphs), key=ord))
    if len(glyphs) != 3755 or len(unique) != 3755:
        raise RuntimeError(
            f"expected 3755 unique GB2312 level-1 Han glyphs, "
            f"found {len(glyphs)} ({len(unique)} unique)"
        )
    return unique


def manifest_glyphs() -> tuple[str, ...]:
    ascii_glyphs = tuple(chr(codepoint) for codepoint in range(0x20, 0x7F))
    punctuation = tuple(sorted(set(CHINESE_PUNCTUATION), key=ord))
    han = gb2312_level_one_han()
    glyphs = ascii_glyphs + punctuation + ("\ufffd",) + han
    if len(set(glyphs)) != len(glyphs):
        raise RuntimeError("font manifest groups overlap")
    return glyphs


def manifest_bytes() -> bytes:
    header = (
        "# Generated by scripts/generate-font-assets.py; do not edit.\n"
        "# Printable ASCII U+0020-U+007E, common Chinese punctuation, then\n"
        "# U+FFFD replacement, then exactly 3755 GB2312 level-1 Han glyphs in Unicode order.\n"
    )
    glyphs = manifest_glyphs()
    ascii_line = "".join(glyphs[:95])
    punctuation_line = "".join(glyphs[95 : 95 + len(set(CHINESE_PUNCTUATION))])
    replacement_index = 95 + len(set(CHINESE_PUNCTUATION))
    han_lines = "".join(f"{glyph}\n" for glyph in glyphs[replacement_index + 1 :])
    return (header + f"{ascii_line}\n{punctuation_line}\n�\n{han_lines}").encode()


def generate_manifest(check: bool) -> None:
    expected = manifest_bytes()
    if check:
        if not MANIFEST_PATH.is_file() or MANIFEST_PATH.read_bytes() != expected:
            raise SystemExit(
                f"{MANIFEST_PATH.relative_to(REPOSITORY_ROOT)} differs from generated output"
            )
        return
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_bytes(expected)


def load_metadata() -> dict[str, object]:
    metadata = json.loads(METADATA_PATH.read_text(encoding="utf-8"))
    if metadata["source_sha256"] != sha256(SOURCE_PATH):
        raise SystemExit(
            f"{SOURCE_PATH.relative_to(REPOSITORY_ROOT)} does not match pinned SHA-256"
        )
    if metadata["license_sha256"] != sha256(LICENSE_PATH):
        raise SystemExit("tracked SIL OFL text does not match pinned SHA-256")
    return metadata


def tool_environment() -> dict[str, str]:
    environment = os.environ.copy()
    existing = environment.get("PYTHONPATH")
    environment["PYTHONPATH"] = (
        str(PYTHON_TOOLS) if not existing else f"{PYTHON_TOOLS}{os.pathsep}{existing}"
    )
    return environment


def verify_tools(metadata: dict[str, object]) -> dict[str, str]:
    tools = metadata["generation_tools"]
    assert isinstance(tools, dict)
    if (
        not PYTHON_TOOLS.is_dir()
        or not LV_FONT_CONV.is_file()
        or not INSTALLED_LV_FONT_CONV_LOCK.is_file()
    ):
        raise SystemExit(
            "missing repository-local generators under work/tools; "
            "see assets/fonts/README.md"
        )
    environment = tool_environment()
    fonttools_version = subprocess.run(
        [sys.executable, "-c", "import fontTools; print(fontTools.__version__)"],
        check=True,
        capture_output=True,
        text=True,
        env=environment,
    ).stdout.strip()
    brotli_version = subprocess.run(
        [sys.executable, "-c", "import brotli; print(brotli.__version__)"],
        check=True, capture_output=True, text=True, env=environment,
    ).stdout.strip()
    lv_version = subprocess.run(
        [str(LV_FONT_CONV), "--version"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()
    if fonttools_version != tools["fonttools"]:
        raise SystemExit(
            f"fontTools {fonttools_version} is installed; expected {tools['fonttools']}"
        )
    if brotli_version != tools["brotli"]:
        raise SystemExit(f"Brotli {brotli_version} is installed; expected {tools['brotli']}")
    if lv_version != tools["lv_font_conv"]:
        raise SystemExit(
            f"lv_font_conv {lv_version} is installed; expected {tools['lv_font_conv']}"
        )
    expected_lock = json.loads(LV_FONT_CONV_LOCK.read_text(encoding="utf-8"))
    installed_lock = json.loads(INSTALLED_LV_FONT_CONV_LOCK.read_text(encoding="utf-8"))
    if installed_lock != expected_lock:
        raise SystemExit("repository-local lv_font_conv dependency tree differs from tracked lock")
    return environment


def run(command: list[str], *, environment: dict[str, str] | None = None) -> None:
    subprocess.run(command, check=True, env=environment)


def normalize_lvgl_c(contents: bytes, payload_bytes: int) -> bytes:
    text = contents.decode().replace("\r\n", "\n")
    text, replacements = re.subn(
        r"^ \* Opts: .*\n",
        " * Source: NotoSansCJKsc-Regular.otf (pinned in assets/fonts/noto-sans-sc.json)\n",
        text,
        count=1,
        flags=re.MULTILINE,
    )
    if replacements != 1:
        raise RuntimeError("lv_font_conv output did not contain its expected options line")
    symbol = re.search(r"^const lv_font_t (micro_ui_sans_\d+) =", text, re.MULTILINE)
    if symbol is None:
        raise RuntimeError("lv_font_conv output did not contain its expected public font symbol")
    text = text.replace(
        f"const lv_font_t {symbol.group(1)} =",
        f"MICRO_UI_SANS_EXPORT const lv_font_t {symbol.group(1)} =",
        1,
    )
    declaration = (
        "/* Generated from pinned Noto Sans CJK SC Regular; do not edit.\n"
        f" * MICRO_UI_SANS_PAYLOAD_BYTES {payload_bytes}\n"
        " * SPDX-License-Identifier: OFL-1.1\n"
        " */\n"
        "#if defined(_WIN32)\n"
        "#define MICRO_UI_SANS_EXPORT __declspec(dllexport)\n"
        "#elif defined(__GNUC__)\n"
        "#define MICRO_UI_SANS_EXPORT __attribute__((visibility(\"default\")))\n"
        "#else\n"
        "#define MICRO_UI_SANS_EXPORT\n"
        "#endif\n"
    )
    return (declaration + text.rstrip() + "\n").encode()


def derive_generation_font(destination: Path, environment: dict[str, str]) -> None:
    """Add U+FFFD as an alias of the pinned source's U+25A1 glyph."""
    script = """
import sys
from fontTools.ttLib import TTFont
font = TTFont(sys.argv[1], recalcTimestamp=False)
mapped = 0
for table in font['cmap'].tables:
    if table.isUnicode() and 0x25A1 in table.cmap:
        table.cmap[0xFFFD] = table.cmap[0x25A1]
        mapped += 1
if not mapped:
    raise SystemExit('pinned source lacks U+25A1 replacement outline')
font.save(sys.argv[2], reorderTables=True)
"""
    run([sys.executable, "-c", script, str(SOURCE_PATH), str(destination)], environment=environment)


def generate_web_font(
    source: Path, destination: Path, glyph_text: Path, environment: dict[str, str]
) -> None:
    run(
        [
            sys.executable,
            "-m",
            "fontTools.subset",
            str(source),
            f"--output-file={destination}",
            "--flavor=woff2",
            f"--text-file={glyph_text}",
            "--layout-features=",
            "--no-hinting",
            "--no-recalc-timestamp",
            "--canonical-order",
            "--name-IDs=0,1,2,3,4,5,6",
            "--name-languages=0x409,0x804",
        ],
        environment=environment,
    )


def verify_web_replacement(font: Path, environment: dict[str, str]) -> None:
    script = """
import sys
from fontTools.ttLib import TTFont
font = TTFont(sys.argv[1])
if not any(0xFFFD in table.cmap for table in font['cmap'].tables if table.isUnicode()):
    raise SystemExit('generated Web font lacks U+FFFD')
"""
    run([sys.executable, "-c", script, str(font)], environment=environment)


def lvgl_font_contains(contents: str, codepoint: int) -> bool:
    lists = {
        name: [int(value, 16) for value in re.findall(r"0x([0-9a-fA-F]+)", values)]
        for name, values in re.findall(
            r"static const uint16_t (unicode_list_\d+)\[\] =\s*\{(.*?)\};",
            contents,
            re.DOTALL,
        )
    }
    for block in re.findall(r"\{\s*\.range_start.*?\}", contents, re.DOTALL):
        start = re.search(r"\.range_start = (\d+)", block)
        length = re.search(r"\.range_length = (\d+)", block)
        unicode_list = re.search(r"\.unicode_list = ([A-Za-z0-9_]+)", block)
        if start is None or length is None or unicode_list is None:
            continue
        offset = codepoint - int(start.group(1))
        if not 0 <= offset < int(length.group(1)):
            continue
        name = unicode_list.group(1)
        if name == "NULL" or offset in lists.get(name, []):
            return True
    return False


def generate_lvgl_font(
    source: Path, size: int, c_destination: Path, bin_destination: Path, glyphs: str
) -> None:
    common = [
        str(LV_FONT_CONV),
        "--size",
        str(size),
        "--bpp",
        str(LVGL_BPP),
        "--font",
        str(source),
        "--symbols",
        glyphs,
        "--no-kerning",
        "--lv-font-name",
        f"micro_ui_sans_{size}",
    ]
    run(
        common
        + ["--format", "lvgl", "--lv-include", "lvgl.h", "-o", str(c_destination)]
    )
    run(common + ["--format", "bin", "-o", str(bin_destination)])


def generate_fonts(check: bool) -> None:
    generate_manifest(check=check)
    metadata = load_metadata()
    environment = verify_tools(metadata)
    glyphs = "".join(manifest_glyphs())
    work_parent = REPOSITORY_ROOT / "work/fonts"
    work_parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="micro-ui-sans-", dir=work_parent) as temporary:
        temporary_directory = Path(temporary)
        glyph_text = temporary_directory / "glyphs.txt"
        glyph_text.write_text(glyphs, encoding="utf-8")
        generation_font = temporary_directory / "NotoSansCJKsc-Regular-with-replacement.otf"
        derive_generation_font(generation_font, environment)
        web_font = temporary_directory / WEB_FONT_PATH.name
        generate_web_font(generation_font, web_font, glyph_text, environment)
        verify_web_replacement(web_font, environment)

        fonts: list[dict[str, object]] = []
        generated_c: dict[int, bytes] = {}
        for size in FONT_SIZES:
            c_font = temporary_directory / f"micro_ui_sans_{size}.c"
            bin_font = temporary_directory / f"micro_ui_sans_{size}.bin"
            generate_lvgl_font(generation_font, size, c_font, bin_font, glyphs)
            if not lvgl_font_contains(c_font.read_text(), ord("\ufffd")):
                raise RuntimeError(f"generated {size}px LVGL font lacks U+FFFD")
            payload_bytes = bin_font.stat().st_size
            contents = normalize_lvgl_c(c_font.read_bytes(), payload_bytes)
            generated_c[size] = contents
            fonts.append(
                {
                    "size_px": size,
                    "path": f"assets/fonts/lvgl/micro_ui_sans_{size}.c",
                    "payload_bytes": payload_bytes,
                    "sha256": hashlib.sha256(contents).hexdigest(),
                }
            )

        declaration = {
            "source_sha256": metadata["source_sha256"],
            "bpp": LVGL_BPP,
            "fonts": fonts,
            "total_payload_bytes": sum(int(font["payload_bytes"]) for font in fonts),
            "web": {
                "path": WEB_FONT_PATH.relative_to(REPOSITORY_ROOT).as_posix(),
                "sha256": sha256(web_font),
            },
        }
        declaration_bytes = (json.dumps(declaration, indent=2) + "\n").encode()

        if check:
            expected = {
                WEB_FONT_PATH: web_font.read_bytes(),
                LVGL_SIZES_PATH: declaration_bytes,
                **{
                    LVGL_DIRECTORY / f"micro_ui_sans_{size}.c": contents
                    for size, contents in generated_c.items()
                },
            }
            mismatches = [
                path.relative_to(REPOSITORY_ROOT).as_posix()
                for path, contents in expected.items()
                if not path.is_file() or path.read_bytes() != contents
            ]
            if mismatches:
                raise SystemExit(
                    "generated font assets differ: " + ", ".join(mismatches)
                )
            return

        WEB_FONT_PATH.parent.mkdir(parents=True, exist_ok=True)
        LVGL_DIRECTORY.mkdir(parents=True, exist_ok=True)
        WEB_FONT_PATH.write_bytes(web_font.read_bytes())
        for size, contents in generated_c.items():
            (LVGL_DIRECTORY / f"micro_ui_sans_{size}.c").write_bytes(contents)
        LVGL_SIZES_PATH.write_bytes(declaration_bytes)


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    for command in ("manifest", "fonts"):
        subparser = subparsers.add_parser(command)
        subparser.add_argument(
            "--check", action="store_true", help="compare tracked output without rewriting"
        )
    return parser.parse_args()


def main() -> None:
    arguments = parse_arguments()
    if arguments.command == "manifest":
        generate_manifest(arguments.check)
    else:
        generate_fonts(arguments.check)


if __name__ == "__main__":
    main()
