#!/usr/bin/env python3
"""Generate compact pinyin -> Hanzi tables for the Micro UI IME.

Produces two headers consumed by the ESP LVGL bridge (placeholder.c):

  assets/fonts/pinyin_table.h
      Single-character candidates: pinyin syllable -> run of Hanzi.

  assets/fonts/pinyin_phrase_table.h
      Common phrases (from jieba's frequency dictionary): full pinyin
      (tone-less) -> the phrase, so "nihao" yields 你好 in one shot.

Only Han covered by the micro_ui_sans_* fonts (the GB2312 level-1 set from
assets/fonts/ui-sans-common.txt) is included, so every candidate renders.

Dependencies (install into the IDF venv): pypinyin, jieba.
"""
import collections
import heapq
import pathlib
import sys

from pypinyin import lazy_pinyin

REPOSITORY_ROOT = pathlib.Path(__file__).resolve().parents[1]
ROOT = REPOSITORY_ROOT
MANIFEST = ROOT / "assets/fonts/ui-sans-common.txt"
manifest = MANIFEST.read_text(encoding="utf-8")
hanzi = [c for c in manifest if "一" <= c <= "鿿"]
hanzi_set = set(hanzi)

PHRASE_LIMIT = 3000  # max phrases to embed
PHRASE_MIN_FREQ = 400  # include common words even if not in the top-N

# Ultra-common everyday words that must always be available, even if their raw
# corpus frequency would push them below the top-N cutoff (e.g. 你好).
CURATED_PHRASES = [
    "你好", "您好", "谢谢", "再见", "再见", "早上好", "晚上好", "对不起",
    "不客气", "没关系", "欢迎", "请问", "帮忙", "朋友", "老师", "学生",
    "工作", "学习", "生活", "时间", "今天", "明天", "昨天", "早上", "晚上",
    "中午", "下午", "现在", "时候", "天气", "下雨", "下雪", "太阳", "月亮",
    "手机", "电脑", "电视", "汽车", "火车", "飞机", "地铁", "商店", "超市",
    "医院", "学校", "饭店", "吃饭", "喝水", "睡觉", "起床", "上班", "下班",
    "回家", "出去", "进来", "一起", "自己", "大家", "我们", "你们", "他们",
    "这个", "那个", "这些", "那些", "什么", "怎么", "为什么", "哪里", "哪个",
    "喜欢", "讨厌", "知道", "觉得", "希望", "需要", "可以", "应该", "可能",
    "漂亮", "好看", "高兴", "开心", "难过", "生气", "认真", "努力", "勇敢",
    "中国", "北京", "上海", "广州", "深圳", "香港", "台湾", "澳门", "英语",
    "中文", "汉字", "拼音", "名字", "号码", "地址", "电话", "邮件", "照片",
    "颜色", "红色", "蓝色", "绿色", "黄色", "白色", "黑色", "红色",
    "问题", "答案", "事情", "东西", "水果", "苹果", "香蕉", "西瓜", "葡萄",
    "蔬菜", "米饭", "面条", "鸡蛋", "牛奶", "咖啡", "茶叶", "啤酒", "白酒",
    "水果", "动物", "小猫", "小狗", "小鸟", "老虎", "狮子", "大象", "熊猫",
    "唱歌", "跳舞", "跑步", "游泳", "运动", "游戏", "电影", "音乐", "唱歌",
    "漂亮", "干净", "安静", "热闹", "新鲜", "美丽", "幸福", "快乐", "健康",
]


def norm(syl: str) -> str:
    return syl.replace("ü", "v")


def pinyin_of(text: str) -> str:
    return "".join(norm(s) for s in lazy_pinyin(text, errors="ignore"))


# ---------------------------------------------------------------------------
# Single-character table
# ---------------------------------------------------------------------------
groups = collections.defaultdict(list)
missing = []
for ch in hanzi:
    found = False
    for syl in lazy_pinyin(ch, errors="ignore"):
        syl = norm(syl)
        if syl and syl.isascii() and syl.isalpha():
            groups[syl].append(ch)
            found = True
    if not found:
        missing.append(ch)

for key in groups:
    groups[key] = list(dict.fromkeys(groups[key]))

print(f"hanzi={len(hanzi)} pinyin_keys={len(groups)} missing={len(missing)}")

lines = []
lines.append("/* Generated by scripts/generate-pinyin-dict.py; do not edit. */")
lines.append("#ifndef MICRO_PINYIN_TABLE_H")
lines.append("#define MICRO_PINYIN_TABLE_H")
lines.append("")
lines.append("typedef struct {")
lines.append("    const char *pinyin;")
lines.append("    const char *candidates;")
lines.append("} micro_pinyin_entry_t;")
lines.append("")
lines.append("static const micro_pinyin_entry_t MICRO_PINYIN_TABLE[] = {")
for key in sorted(groups):
    lines.append(f'    {{"{key}", "{''.join(groups[key])}"}},')
lines.append("};")
lines.append("")
lines.append("static const unsigned MICRO_PINYIN_TABLE_LEN =")
lines.append("    sizeof(MICRO_PINYIN_TABLE) / sizeof(MICRO_PINYIN_TABLE[0]);")
lines.append("")
lines.append("#endif")
out = ROOT / "assets/fonts/pinyin_table.h"
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {out} ({out.stat().st_size} bytes)")

# ---------------------------------------------------------------------------
# Phrase table (jieba frequency dictionary, filtered to font coverage)
# ---------------------------------------------------------------------------
try:
    import jieba
    jieba.initialize()
    freq = jieba.dt.FREQ
except Exception as exc:  # pragma: no cover - depends on dev environment
    print(f"WARNING: jieba unavailable, skipping phrase table: {exc}", file=sys.stderr)
    raise SystemExit(0)

phrase_rows = []
for word, count in freq.items():
    if count < PHRASE_MIN_FREQ:
        continue
    if not (2 <= len(word) <= 3):
        continue
    if not all(c in hanzi_set for c in word):
        continue
    py = pinyin_of(word)
    if not py or len(py) > 12:
        continue
    phrase_rows.append((count, word, py))

# Curated everyday words are guaranteed in; fill the rest by frequency.
best_by_pinyin: dict[str, str] = {}
for word in CURATED_PHRASES:
    if all(c in hanzi_set for c in word):
        best_by_pinyin.setdefault(pinyin_of(word), word)

# Keep the most frequent phrases; de-dupe by pinyin keeping the top word.
phrase_rows.sort(reverse=True)
for count, word, py in phrase_rows:
    if py in best_by_pinyin:
        continue
    best_by_pinyin[py] = word
    if len(best_by_pinyin) >= PHRASE_LIMIT:
        break

lines = []
lines.append("/* Generated by scripts/generate-pinyin-dict.py; do not edit. */")
lines.append("#ifndef MICRO_PINYIN_PHRASE_TABLE_H")
lines.append("#define MICRO_PINYIN_PHRASE_TABLE_H")
lines.append("")
lines.append("typedef struct {")
lines.append("    const char *pinyin;")
lines.append("    const char *phrase;")
lines.append("} micro_pinyin_phrase_t;")
lines.append("")
lines.append("static const micro_pinyin_phrase_t MICRO_PINYIN_PHRASES[] = {")
for py in sorted(best_by_pinyin):
    lines.append(f'    {{"{py}", "{best_by_pinyin[py]}"}},')
lines.append("};")
lines.append("")
lines.append("static const unsigned MICRO_PINYIN_PHRASES_LEN =")
lines.append("    sizeof(MICRO_PINYIN_PHRASES) / sizeof(MICRO_PINYIN_PHRASES[0]);")
lines.append("")
lines.append("#endif")
out = ROOT / "assets/fonts/pinyin_phrase_table.h"
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {out} ({out.stat().st_size} bytes, {len(best_by_pinyin)} phrases)")
